In [2]:
import json

import pandas as pd

### 从csv中导入

In [3]:
df = pd.read_csv('../mock_sales_data.csv')
df

,order_id,date,customer,region,category,product,quantity,unit_price,total,status
0,ORD0001,2025-11-24,徐明先生,华南,电子产品,手机,9,1228.23,11054.07,已取消
1,ORD0002,2025-10-30,张伟,华南,家居用品,台灯,1,473.01,473.01,已完成
2,ORD0003,2025-04-12,张伟先生,华北,运动户外,手套,8,2248.80,17990.40,配送中
3,ORD0004,2025-08-05,李娜女士,东北,食品饮料,咖啡,5,1080.49,5402.45,已完成
4,ORD0005,2025-02-19,徐明先生,华东,食品饮料,坚果,20,1326.28,26525.60,已取消
...,...,...,...,...,...,...,...,...,...,...
95,ORD0096,2025-04-30,周丽先生,华南,食品饮料,茶叶,14,578.31,8096.34,待发货
96,ORD0097,2025-02-06,吴鑫女士,东北,电子产品,耳机,10,2977.24,29772.40,待发货
97,ORD0098,2025-03-05,何勇先生,西南,家居用品,拖鞋,13,4713.67,61277.71,已完成
98,ORD0099,2025-11-03,高洁,华东,电子产品,鼠标,11,3020.55,33226.05,已完成
99,ORD0100,2025-01-11,孙艳,东北,运动户外,背包,19,205.96,3913.24,已完成

### 从json中导入

In [10]:
# df = pd.read_json('../mock_sales_data.json')
# df
import json
with open('../mock_sales_data.json','r') as f:
    data = json.load(f)
df = pd.DataFrame(data['sales'])
df

,order_id,date,customer,region,category,product,quantity,unit_price,total,status
0,ORD0001,2025-11-24,陈静,华东,电子产品,手机,9,1228.23,11054.07,待发货
1,ORD0002,2025-10-07,赵敏先生,西南,电子产品,鼠标,2,153.84,307.68,待发货
2,ORD0003,2025-10-15,周丽先生,东北,服装鞋帽,连衣裙,8,2248.80,17990.40,配送中
3,ORD0004,2025-08-05,马超先生,华东,食品饮料,咖啡,5,1080.49,5402.45,已完成
4,ORD0005,2025-07-03,徐明先生,华中,食品饮料,咖啡,2,3650.01,7300.02,已完成
...,...,...,...,...,...,...,...,...,...,...
95,ORD0096,2025-02-11,杨磊先生,华中,服装鞋帽,羽绒服,6,2762.20,16573.20,已完成
96,ORD0097,2025-11-01,吴鑫,东北,家居用品,拖鞋,2,1161.22,2322.44,已完成
97,ORD0098,2025-04-30,黄强,华南,食品饮料,茶叶,14,578.31,8096.34,待支付
98,ORD0099,2025-03-14,梁平,东北,电子产品,手机,6,3964.18,23785.08,待发货
99,ORD0100,2025-05-28,胡涛女士,西南,家居用品,抱枕,15,3444.95,51674.25,已完成