In [4]:
import pandas as pd
pd.__version__

'3.0.3'

In [16]:
df = pd.read_csv('../employees_salary.csv')
g1 = df.groupby('部门') #查看分组
g1.get_group("人事部") # 查看详情
g1[['工资(元)']].mean().round(2)

       员工编号    姓名   部门  工资(元)
0   EMP0008    李涛  产品部   5582
1   EMP0018    高娟  产品部  14861
2   EMP0034   赵娟军  产品部  16470
3   EMP0040    朱明  产品部   4921
4   EMP0046    罗芳  产品部  24540
5   EMP0007    赵军  人事部  29447
6   EMP0013    黄丽  人事部  23971
7   EMP0017    刘磊  人事部  27478
8   EMP0021    马慧  人事部  21128
9   EMP0022    张敏  人事部  28185
10  EMP0023   陈涛伟  人事部  19403
11  EMP0024    陈超  人事部  23937
12  EMP0041   马洋涛  人事部  16861
13  EMP0047    高华  人事部   9693
14  EMP0002    刘敏  市场部  22349
15  EMP0006   杨勇敏  市场部  15449
16  EMP0015    李勇  市场部   9913
17  EMP0019    黄静  市场部  27765
18  EMP0020   陈娟慧  市场部  15608
19  EMP0035    胡芳  市场部   4986
20  EMP0036    马勇  市场部  11147
21  EMP0038    陈洋  市场部  17520
22  EMP0044    郭娜  市场部  22498
23  EMP0049    王伟  市场部   5400
24  EMP0003   杨磊超  技术部  21390
25  EMP0014    何磊  技术部  10505
26  EMP0025  孙丽秀英  技术部  22626
27  EMP0026   孙艳磊  技术部  10892
28  EMP0030   黄娜勇  技术部  22277
29  EMP0031    何磊  技术部   5326
30  EMP0042   吴强芳  技术部  27509
31  EMP0004   杨秀英  行政部  22309
32  EMP0033    林强  行政部  10962
33  EMP0001    赵伟  财务部  10314
34  EMP0010   黄艳娜  财务部   6309
35  EMP0028   郭慧娟  财务部  20671
36  EMP0032   李勇娜  财务部  12125
37  EMP0039   何伟娜  财务部   8449
38  EMP0045    王磊  财务部  21970
39  EMP0009    何艳  运营部  21918
40  EMP0011    马洋  运营部   8329
41  EMP0029    杨艳  运营部  17355
42  EMP0048   刘艳涛  运营部  27637
43  EMP0005    周伟  销售部  25876
44  EMP0012   周娜慧  销售部  20502
45  EMP0016   林杰涛  销售部  11679
46  EMP0027  林娜秀英  销售部   7207
47  EMP0037    杨强  销售部  16824
48  EMP0043   林超超  销售部   4863
49  EMP0050    何强  销售部  14436

In [23]:
## 多个列进行分组
g2 = df.groupby(['姓名','部门'])
g2[['工资(元)']].mean().sort_values("工资(元)",ascending=False)

            工资(元)
姓名   部门
赵军   人事部  29447.0
张敏   人事部  28185.0
黄静   市场部  27765.0
刘艳涛  运营部  27637.0
吴强芳  技术部  27509.0
刘磊   人事部  27478.0
周伟   销售部  25876.0
罗芳   产品部  24540.0
黄丽   人事部  23971.0
陈超   人事部  23937.0
孙丽秀英 技术部  22626.0
郭娜   市场部  22498.0
刘敏   市场部  22349.0
杨秀英  行政部  22309.0
黄娜勇  技术部  22277.0
王磊   财务部  21970.0
何艳   运营部  21918.0
杨磊超  技术部  21390.0
马慧   人事部  21128.0
郭慧娟  财务部  20671.0
周娜慧  销售部  20502.0
陈涛伟  人事部  19403.0
陈洋   市场部  17520.0
杨艳   运营部  17355.0
马洋涛  人事部  16861.0
杨强   销售部  16824.0
赵娟军  产品部  16470.0
陈娟慧  市场部  15608.0
杨勇敏  市场部  15449.0
高娟   产品部  14861.0
何强   销售部  14436.0
李勇娜  财务部  12125.0
林杰涛  销售部  11679.0
马勇   市场部  11147.0
林强   行政部  10962.0
孙艳磊  技术部  10892.0
赵伟   财务部  10314.0
李勇   市场部   9913.0
高华   人事部   9693.0
何伟娜  财务部   8449.0
马洋   运营部   8329.0
何磊   技术部   7915.5
林娜秀英 销售部   7207.0
黄艳娜  财务部   6309.0
李涛   产品部   5582.0
王伟   市场部   5400.0
胡芳   市场部   4986.0
朱明   产品部   4921.0
林超超  销售部   4863.0