In [1]:
import pandas as pd

In [21]:
df = pd.read_csv('../sleep_survey.csv')
df = df.ffill().bfill()
df.isna().sum()
df.describe()

,年龄,睡眠时长_小时,睡眠质量评分_1_10,午睡时长_分钟,咖啡因_杯_天,压力水平_1_10,屏幕时间_睡前_小时,BMI
count,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,41.142000,6.690000,3.330000,12.290000,2.03340,5.382000,2.514000,23.401800
std,13.911898,1.271035,1.260268,19.252304,1.37317,2.061207,1.244339,3.915323
min,18.000000,3.000000,1.000000,0.000000,0.00000,1.000000,0.000000,16.000000
25%,29.000000,5.900000,2.000000,0.000000,0.90000,4.000000,1.600000,20.500000
50%,40.000000,6.750000,4.000000,0.000000,2.00000,5.000000,2.500000,23.200000
75%,53.000000,7.600000,4.000000,23.000000,3.10000,7.000000,3.400000,26.000000
max,65.000000,10.000000,5.000000,82.000000,5.10000,10.000000,6.000000,35.500000

In [22]:
g1 = df.groupby("年龄")
df2 = g1.agg({
    '睡眠时长_小时': ['min','max']
})
df2[df2.index>45]

     睡眠时长_小时
         min  max
年龄
46.0     4.4  7.9
47.0     3.2  9.2
48.0     4.8  8.8
49.0     4.8  7.7
50.0     4.2  6.8
51.0     3.8  8.7
52.0     3.8  8.2
53.0     4.5  8.9
54.0     5.0  8.3
55.0     5.4  9.1
56.0     3.1  7.3
57.0     5.5  8.9
58.0     4.7  8.1
59.0     4.3  7.8
60.0     4.8  7.6
61.0     5.0  8.4
62.0     3.9  7.4
63.0     3.1  8.3
64.0     5.5  7.6
65.0     3.4  8.2